export const COMPANY_COLOR = "#0058A7";

export const colors = {
  primary01: "rgb(var(--color-primary01)  / <alpha-value>)",
  primary02: "rgb(var(--color-primary02)  / <alpha-value>)",
  primary03: "rgb(var(--color-primary03)  / <alpha-value>)",
  neutral0: "rgb(var(--color-neutral0)  / <alpha-value>)",
  neutral10: "rgb(var(--color-neutral10)  / <alpha-value>)",
  neutral20: "rgb(var(--color-neutral20)  / <alpha-value>)",
  neutral30: "rgb(var(--color-neutral30)  / <alpha-value>)",
  neutral40: "rgb(var(--color-neutral40)  / <alpha-value>)",
  neutral50: "rgb(var(--color-neutral50)  / <alpha-value>)",
  neutral60: "rgb(var(--color-neutral60)  / <alpha-value>)",
  neutral70: "rgb(var(--color-neutral70)  / <alpha-value>)",
  neutral80: "rgb(var(--color-neutral80)  / <alpha-value>)",
  neutral90: "rgb(var(--color-neutral90)  / <alpha-value>)",
  neutral100: "rgb(var(--color-neutral100)  / <alpha-value>)",
  blue: "rgb(var(--color-blue)  / <alpha-value>)",
  green: "rgb(var(--color-green)  / <alpha-value>)",
  yellow: "rgb(var(--color-yellow)  / <alpha-value>)",
  orange: "rgb(var(--color-orange)  / <alpha-value>)",
  red: "rgb(var(--color-red)  / <alpha-value>)",
  mint: "rgb(var(--color-mint)  / <alpha-value>)",
  teal: "rgb(var(--color-teal)  / <alpha-value>)",
  cyan: "rgb(var(--color-cyan)  / <alpha-value>)",
  indigo: "rgb(var(--color-indigo)  / <alpha-value>)",
  purple: "rgb(var(--color-purple)  / <alpha-value>)",
  pink: "rgb(var(--color-pink)  / <alpha-value>)",
  brown: "rgb(var(--color-brown)  / <alpha-value>)",
  lightblue: "rgb(var(--color-lightblue)  / <alpha-value>)",
} as const;

export const colorString = {
  primary01: "rgb(var(--color-primary01)",
  primary02: "rgb(var(--color-primary02)",
  primary03: "rgb(var(--color-primary03)",
  neutral0: "rgb(var(--color-neutral0)",
  neutral10: "rgb(var(--color-neutral10)",
  neutral20: "rgb(var(--color-neutral20)",
  neutral30: "rgb(var(--color-neutral30)",
  neutral40: "rgb(var(--color-neutral40)",
  neutral50: "rgb(var(--color-neutral50)",
  neutral60: "rgb(var(--color-neutral60)",
  neutral70: "rgb(var(--color-neutral70)",
  neutral80: "rgb(var(--color-neutral80)",
  neutral90: "rgb(var(--color-neutral90)",
  neutral100: "rgb(var(--color-neutral100)",
  blue: "rgb(var(--color-blue)",
  green: "rgb(var(--color-green)",
  yellow: "rgb(var(--color-yellow)",
  orange: "rgb(var(--color-orange)",
  red: "rgb(var(--color-red)",
  mint: "rgb(var(--color-mint)",
  teal: "rgb(var(--color-teal)",
  cyan: "rgb(var(--color-cyan)",
  indigo: "rgb(var(--color-indigo)",
  purple: "rgb(var(--color-purple)",
  pink: "rgb(var(--color-pink)",
  brown: "rgb(var(--color-brown)",
  lightblue: "rgb(var(--color-lightblue)",
} as const;
